### ISSUE TITLE
還是不成

### ISSUE THREAD

**Issue by mk2leo** [ameizi/52pojie_sign_bot#2]
## 开始执行... 2023-03-06 10:54:40

Cookie 失效
52pojie签到

Cookie 失效

COOKIE是即時的.

**Comment by v5tech** [comment]
退出登陆后，获取个新的Cookie再试试看。拷贝完整的Cookie值 @mk2leo

**Comment by mk2leo** [comment]
> 退出登陆后，获取个新的Cookie再试试看。拷贝完整的Cookie值 @mk2leo

试了.还是一样错误..会不会有些参数.只能供你ID识别

**Comment by v5tech** [comment]
> > 退出登陆后，获取个新的Cookie再试试看。拷贝完整的Cookie值 @mk2leo
> 
> 试了.还是一样错误..会不会有些参数.只能供你ID识别

不会啊，我就是担心解析Cookie的代码不能通用，这里专门使用了正则表达式去提取`_saltkey`和`_auth`的Cookie值，经测试只要Cookie中包含这两个键值都是可以正常登陆的。

实在不行了，你把代码克隆到本地在本地调试下。

着重观察这里解析Cookie的时候，Cookie中包含的`/`、`+`特殊字符有没有进行编码。

<img width="561" alt="image" src="https://user-images.githubusercontent.com/887836/223670982-2f64608a-18fb-4a5b-95ff-67d8bc0107c4.png">

**Comment by mk2leo** [comment]
> > > 退出登陆后，获取个新的Cookie再试试看。拷贝完整的Cookie值 @mk2leo
> > 
> > 
> > 试了.还是一样错误..会不会有些参数.只能供你ID识别
> 
> 不会啊，我就是担心解析Cookie的代码不能通用，这里专门使用了正则表达式去提取`_saltkey`和`_auth`的Cookie值，经测试只要Cookie中包含这两个键值都是可以正常登陆的。
> 
> 实在不行了，你把代码克隆到本地在本地调试下。
> 
> 着重观察这里解析Cookie的时候，Cookie中包含的`/`、`+`特殊字符有没有进行编码。
> 
> <img alt="image" width="561" src="https://user-images.githubusercontent.com/887836/223670982-2f64608a-18fb-4a5b-95ff-67d8bc0107c4.png">

![image](https://user-images.githubusercontent.com/72913711/223927514-9efcab8d-6d93-49d9-a76c-4327c6429438.png)

我本地跑的.你看看提取的值有問題嗎

**Comment by v5tech** [comment]
> > > > 退出登陆后，获取个新的Cookie再试试看。拷贝完整的Cookie值 @mk2leo
> > > 
> > > 
> > > 试了.还是一样错误..会不会有些参数.只能供你ID识别
> > 
> > 
> > 不会啊，我就是担心解析Cookie的代码不能通用，这里专门使用了正则表达式去提取`_saltkey`和`_auth`的Cookie值，经测试只要Cookie中包含这两个键值都是可以正常登陆的。
> > 实在不行了，你把代码克隆到本地在本地调试下。
> > 着重观察这里解析Cookie的时候，Cookie中包含的`/`、`+`特殊字符有没有进行编码。
> > <img alt="image" width="561" src="https://user-images.githubusercontent.com/887836/223670982-2f64608a-18fb-4a5b-95ff-67d8bc0107c4.png">
> 
> ![image](https://user-images.githubusercontent.com/72913711/223927514-9efcab8d-6d93-49d9-a76c-4327c6429438.png)
> 
> 我本地跑的.你看看提取的值有問題嗎

从你的截图反馈来看，获取到的Cookie是可以正常使用的呢。
